### ISSUE TITLE
Resolving IMA hash, still results in measurement failure.

### ISSUE THREAD

**Issue by lukehinds** [keylime/python-keylime#110]
# Upstream issue

# Environment
 * OS / version: Fedora 29
 * Processor architecture: x86_64
 * TPM Manufacturer: Intel
 * Keylime version: master

# Description 

**This is an upstream issue**, but wanted to discuss it here in case its policy related, or experienced before by someone here.

Provision verifier with a whitelist and make sure IMA measurements are active.

`cp /usr/bin/ping /root/ping-good`
`cp /usr/bin/ping /root/ping-bad`

capture the good hash:

```
sha1sum /usr/bin/ping
d1703bf9c9d7094c0e9aacb634002ffa447ec02e  /usr/bin/ping
```

Change a single byte in `ping-bad` (enough to change the hash)

```
sha1sum ping-* 
08456d1e7b73d654a0fadd096258804a98b5bd4d  ping-bad
d1703bf9c9d7094c0e9aacb634002ffa447ec02e  ping-good
````
Put the bad file into place (replicating what a trojan would do)

`cp /root/ping-bad /usr/bin/ping`
Now exec:

`ping localhost`

As expected, IMA fails:

```
WARNING - Hashes for file /usr/bin/ping don't match 08456d1e7b73d654a0fadd096258804a98b5bd4d not in [u'd1703bf9c9d7094c0e9aacb634002ffa447ec02e', u'd1703bf9c9d7094c0e9aacb634002ffa447ec02e', u'd1703bf9c9d7094c0e9aacb634002ffa447ec02e', u'd1703bf9c9d7094c0e9aacb634002ffa447ec02e']
```
Now copy the good file back:

`cp /root/ping-bad /usr/bin/ping`

```
sha1sum /usr/bin/ping
d1703bf9c9d7094c0e9aacb634002ffa447ec02e  /usr/bin/ping
```

Delete and re-add the agent

Agent still fails IMA, even though the good file / correct hash is in place:

```
WARNING - Hashes for file /usr/bin/ping don't match 08456d1e7b73d654a0fadd096258804a98b5bd4d not in [u'd1703bf9c9d7094c0e9aacb634002ffa447ec02e', u'd1703bf9c9d7094c0e9aacb634002ffa447ec02e', u'd1703bf9c9d7094c0e9aacb634002ffa447ec02e', u'd1703bf9c9d7094c0e9aacb634002ffa447ec02e']
```

Check the IMA measurement file

```
cat /sys/kernel/security/ima/ascii_runtime_measurements|grep ping
10 4b0fdc36d52e6a084ecd9600511eb1b8899e0f66 ima-ng sha1:d1703bf9c9d7094c0e9aacb634002ffa447ec02e /usr/bin/ping
10 dfed582395942b2a93adfa6b98191cd34211b25c ima-ng sha1:08456d1e7b73d654a0fadd096258804a98b5bd4d /root/ping-bad
10 e1bc1e2ef8c14dc0276a9be84aef549cc1a4dfbc ima-ng sha1:08456d1e7b73d654a0fadd096258804a98b5bd4d /usr/bin/ping
```

So its not updating for some reason?

**Comment by jetwhiz** [comment]
Deleting and re-adding the agent should not make it pass its IMA attestation, since the machine is forever considered in a bad state after the unauthorized ping command has been run.  The only way to bring the node back into a good state is to fully reboot the node so it is in a trustworthy state again.

**Comment by lukehinds** [comment]
Happy with that answer, makes sense.
