### ISSUE TITLE
Gitter chat badge for readme.

### ISSUE THREAD

**Issue by lukehinds** [keylime/python-keylime#34]
# Description 

Implement readme badge for users to find the keylime gitter.im channel

Some decent badges can be used from [shields.io](https://shields.io/)

**Comment by jetwhiz** [comment]
Has this already been fixed?

**Comment by lukehinds** [comment]
It has, forgot to tag this issue in the commit: https://github.com/keylime/python-keylime/commit/74ba7b5bd87bedbe288e70115618a205dc625871
