### ISSUE TITLE
Check for existing secure mount

### ISSUE THREAD

**Issue by lukehinds** [keylime/python-keylime#36]
# Environment
 * OS / version: N/A
 * Processor architecture: N/A
 * TPM Manufacturer: N/A
 * Keylime version: master

# Description 

A majority of distributions mount a secure volume be default to:

`securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)`

We create our own in `/var/lib/keylime/secure` [here](https://github.com/keylime/python-keylime/blob/master/keylime/secure_mount.py#L53)

I guess this might already be factored in and there is a reason for this, if not we could perhaps check for the existing mount and if its configured correctly and present, we can use that instead.

Tagging @jetwhiz

**Comment by jetwhiz** [comment]
Hi @lukehinds 

I think that's a good idea, maybe we can mount to /sys/kernel/security/keylime or similar if we detect that the securityfs is already mounted by the OS.

**Comment by lukehinds** [comment]
I think this issue maybe flawed so going to close. I just read a bit more about securityfs

> Some observers might well believe that the kernel has accumulated plenty of special-purpose virtual filesystems. Even so, 2.6.14 will include yet another one: securityfs. This filesystem is meant to be used by security modules, some of which were otherwise creating their own filesystems; it should be mounted on /sys/kernel/security. Securityfs thus looks, from user space, like part of sysfs, but it is a distinct entity.
> The API for securityfs is quite simple - it only exports three functions (defined in <linux/security.h>). The usual first step will be to create a directory specific to the security module at hand with:
> 
>     struct dentry *securityfs_create_dir(const char *name, 
>                                          struct dentry *parent);
> 

https://lwn.net/Articles/153366/
