### ISSUE TITLE
Project Logo

### ISSUE THREAD

**Issue by lukehinds** [keylime/python-keylime#52]
You may have noticed I tried out some project logos. I think in the interest of it being a community decision I share out what I got from some colleagues and we choose together.

I currently like C

![](https://i.imgur.com/w54SofM.png)
![](https://i.imgur.com/VsJnT13.png)

**Comment by lukehinds** [comment]
@jetwhiz 
@nabilschear 
@frozencemetery
@leonjia0112
@mbestavros

Let me know your preferred logo.

Note, this does not have to be fixed, if someone in the future comes along with something better, all it takes is a PR and another vote.  I just think it looks better to have something, instead of the default avatar thing github provides.

**Comment by jetwhiz** [comment]
These look really nice, @lukehinds!  I agree with C as my favorite, since I typically go for simpler-looking logos.

**Comment by nabilschear** [comment]
FYI: we've got a graphic artist that we can tap to help us with this.  should i send him these options?

**Comment by lukehinds** [comment]
@nabilschear , sure, or he can come up with his own as well. 

It just need to be something simple, that will work on websites, stickers etc. 

For example: https://github.com/PyCQA/bandit/pull/302

**Comment by frozencemetery** [comment]
Nice!  I think B and C are my favorites because they keep the number of colors small.

**Comment by lukehinds** [comment]
So look like C for now (which is useful as I already have that one up)!

**Comment by leonjia0112** [comment]
My vote is C. But I think a different green color would be better since the current green is a little too bright. Maybe like the of github's Comment button :)

**Comment by lukehinds** [comment]
Good points @leonjia0112 , a PR can be made is you prefer a different shade of green :+1:
