### ISSUE TITLE
keylime_ima_emulator incorrectly parses token from ascii_runtime_measurements

### ISSUE THREAD

**Issue by lukehinds** [keylime/python-keylime#62]
# Environment
 * OS / version: Fedora 29
 * Processor architecture:  N/A
 * TPM Manufacturer: emulator
 * Keylime version:  master

# Description 

When running the keylime_ima_emulator service, some lines of `ascii_runtime_measurements` are incorrectly split.

`Feb 27 16:59:43 localhost.localdomain tpm_with_ima.sh[11418]: ERROR: invalid measurement list file line: -7ec02e /usr/bin/ping-`

`cat /sys/kernel/security/ima/ascii_runtime_measurements |grep ping
10 4b0fdc36d52e6a084ecd9600511eb1b8899e0f66 ima-ng sha1:d1703bf9c9d7094c0e9aacb634002ffa447ec02e /usr/bin/ping
`

This is from the following code:

https://github.com/keylime/python-keylime/blob/aa2b55aba7eab9924b3b0f23cd07bbf726ef30ac/keylime/ima_emulator_adapter.py#L41-L49

## Steps to reproduce problem
1.  Run  keylime_ima_emulator against the following list:

https://paste.fedoraproject.org/paste/RggKZQRNMbL2qCWTrmqisA

**Comment by lukehinds** [comment]
Just assigning you so that you get notifications @jetwhiz 

This one is perplexing:

If I copy `/sys/kernel/security/ima/ascii_runtime_measurements` to say for example `/root/ascii_runtime_measurements` then make the following change:

`
def ml_extend(ml,position,searchHash=None):
    ml='/root/ascii_runtime_measurements'
    f = open(ml,'r')
`

Everything works. It seems there is something specific about the nature of file in `/sys/kernel/security` that is throwing this off. 

I will keep digging.

**Comment by nabilschear** [comment]
is securityfs proving half of a line?  maybe we need to make sure that we've got a whole line.

**Comment by lukehinds** [comment]
Good point. I think I will try grabbing the next line down to see if it's the second half of a troublesome line.

**Comment by lukehinds** [comment]
This seems to be related to `f.seek(position` - I can't qualify why yet, but I believe its from the file being updated and shifting line numbers.

**Comment by lukehinds** [comment]
@nabilschear / @jetwhiz  - well using Fedora 28 the issue does not exist. 

I will now try and work out the differentiate by looking through commits to the IMA kernel code and possibly Fedoras kernel compile configs.

One point I wanted to query you on. Using the ima_emulator, it takes a long time for all the hashes to extend. I guess this might be from the sleep call being used within the while loop that iterates over the lines. So I expect things would be a bit quicker with a hardware TPM, but still some delay would be involved perhaps - with that in mind would it be a concern to boot up times or ensuring the list is populated fully before a system is online to run its services to uses. I say this especially with vm's / containers in mind,  that are expected to be available in seconds.

**Comment by lukehinds** [comment]
I spoke to soon, same issue on Fedora 28.

**Comment by lukehinds** [comment]
Another quick update, the issue seems to be specific to the Fedora Cloud Images (qcow2). 

I have metal instance of Fedora 29 and the weird line chopping does not occur.

I am now going to try to same on some other dists deployed as VM's. That way we can outrule if its a virtualized anomaly or something specific to Fedora 29 cloud.

It's still worth pursuing this as most of the big cloud providers use the Fedora cloud images, so we will need this fixed / resolved for vTPM.

**Comment by lukehinds** [comment]
Update: Issue not present on Ubuntu, trying out some ideas before confirming what I think the issue might be.
