### ISSUE TITLE
Team weekly meeting

### ISSUE THREAD

**Issue by lukehinds** [keylime/python-keylime#68]
@nabilschear @jetwhiz @frozencemetery @leonjia0112 @mbestavros 

It would be good to have a short and to the point meeting online (gitter.im) once a week (we can push out to 2 weeks if excessive). 

please indicate a time that would work for you, don't worry if you cannot make next week specifically, this would be as an ongoing thing. if anytime on a Wednesday does not work, let me know and I can shift it to another day.

https://doodle.com/poll/fz3sap7iubufbstt

**Comment by leonjia0112** [comment]
Submitted :+1:

**Comment by lukehinds** [comment]
I will let this run until Friday and then go with the highest approved time on the doodle poll. We can then have our first meeting on Wednesday the 13th of March!

**Comment by lukehinds** [comment]
So the most popular time is 15:00 to 15:30 [UTC time](https://www.timeanddate.com/worldclock/timezone/utc). Our first meeting will be on 13th March and repeating weekly. I will set up an agenda shortly. 

Closing this issue now.
