### ISSUE TITLE
pyyaml dependency handling

### ISSUE THREAD

**Issue by nabilschear** [keylime/python-keylime#81]
# Environment
 * OS / version: mac osx
 * Processor architecture: 
 * TPM Manufacturer: 
 * Keylime version: 

# Description 

pyyaml dependency wasn't handled the same way in setup.py and installer.sh as our other dependencies.  So, when i work with keylime on my mac with the emulator the yaml dependency wasn't pulled in by setup.py

## Expected behavior vs. actual behavior 
 expected: keylime runs
actual: import yaml not found error

## Steps to reproduce problem
1. create virtual environment
2. activate virtual environment
3. python setup.py install
4. attempt to run any of the keylime applications

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by nabilschear** [comment]
this is also related to #80

**Comment by lukehinds** [comment]
I think we are good to close this one too @nabilschear ?

**Comment by nabilschear** [comment]
agreed
