### ISSUE TITLE
config value for TPM type

### ISSUE THREAD

**Issue by lukehinds** [keylime/python-keylime#84]
# Environment
 * OS / version: n/a
 * Processor architecture: x86
 * TPM Manufacturer: n/a
 * Keylime version: master

# Description 

Currently we establish tpm version by querying the environment path.

I think this is a pefectly valid way of doing this, but it can result in a somewhat edge case I had earlier where I had both tool versions installed, yet was running a TPM 2.0 emulator, each time I started the cloud node, it found `getcapability` and as this is the first check in the if conditional statement, `1` is returned and the node failed to connect.

https://github.com/keylime/python-keylime/blob/d277757199a555f78dde69cca366557e232f9cfa/keylime/tpm_obj.py#L50-L51

## Expected behavior vs. actual behavior 

I would recommend we add a config value in `keylime.conf` to allow someone to overide the path check with a set value. We can leave this commented out as per default, so the path check works to discover the version we are using. If however, for some reason someone does have both toolsets deployed, they can set their own preference. 

## Steps to reproduce problem
1. Install both tpm1 and tpm2 tools 
2. Start the TPM 2.0 emulator.

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by nabilschear** [comment]
@lukehinds this is my fault.  @jetwhiz used to have a config var for this.  i suggested that we auto-detect.  I thought that the only case where it would be strange is if you have both sets of tools installed *and* both emulators running.  In that case, it would default to tpm1.2.  However, in your case it should default to tpm2.

**Comment by lukehinds** [comment]
hey no ones fault, it makes sense why it was designed like this. I am happy to take this one on and set a config again if that sounds ok to you?

**Comment by nabilschear** [comment]
i was against having a config var.  i think keylime should just work out of the box.  In your case, there may be something wrong with the logic above.  Are you actually running both emulators?

**Comment by nabilschear** [comment]
@lukehinds actually i think this logic isn't working right.  let me take a look

**Comment by nabilschear** [comment]
it's a bit ugly.  on my machine i get this when i have tpm1.2 tools installed but no emulator running:
```
WARNING: running without root access
Using config file ../keylime.conf
1552676124.61 - keylime.cloudnode - WARNING - unable to log to /dev/console. please run as root
1552676125.02 - keylime.tpm1 - INFO - Failed to call TPM 1/10 times, trying again in 1.000000 seconds...
1552676126.04 - keylime.tpm1 - INFO - Failed to call TPM 2/10 times, trying again in 1.000000 seconds...
1552676127.06 - keylime.tpm1 - INFO - Failed to call TPM 3/10 times, trying again in 1.000000 seconds...
1552676128.08 - keylime.tpm1 - INFO - Failed to call TPM 4/10 times, trying again in 1.000000 seconds...
1552676129.1 - keylime.tpm1 - INFO - Failed to call TPM 5/10 times, trying again in 1.000000 seconds...
1552676130.12 - keylime.tpm1 - INFO - Failed to call TPM 6/10 times, trying again in 1.000000 seconds...
1552676131.14 - keylime.tpm1 - INFO - Failed to call TPM 7/10 times, trying again in 1.000000 seconds...
1552676132.15 - keylime.tpm1 - INFO - Failed to call TPM 8/10 times, trying again in 1.000000 seconds...
1552676133.17 - keylime.tpm1 - INFO - Failed to call TPM 9/10 times, trying again in 1.000000 seconds...
1552676134.18 - keylime.tpm1 - ERROR - TPM appears to be in use by another application.  Keylime is incompatible with other TPM TSS applications like trousers/tpm-tools. Please uninstall or disable.
```

So, it tries a bunch of times.  This is because it returns an I/O error, which causes keylime to keep trying.  Then it finally does start working and using tpm2 tools.

**Comment by nabilschear** [comment]
since this is really only relevant for the emulator, i'm tempted not to worry about it.  But that assumes that you actually get the behavior above.

**Comment by lukehinds** [comment]
mine was just from not cleaning down an environment. so this is an edge case and a very rare one, so I am happy to close this.
