### ISSUE TITLE
use of `raise Exception`

### ISSUE THREAD

**Issue by lukehinds** [keylime/python-keylime#87]
Within `tenant.py` we use `raise Exception` and I wonder if this is needed in all cases.

For example we may see the following:

```
1552982503.81 - keylime.cloudverifier - WARNING - Node of uuid D432FBB3-D2F1-4A97-9EF7-75BD81C00000 already exists
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/tenant.py", line 744, in main
    mytenant.do_cv()
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/tenant.py", line 481, in do_cv
    raise Exception("Node %s already existed at CV.  Please use delete or update."%self.node_uuid)
Exception: Node D432FBB3-D2F1-4A97-9EF7-75BD81C00000 already existed at CV.  Please use delete or update.
```

The use of `raise Exception` here makes it look like the code is broken as we get a traceback as CLI output, but in fact the code has captured the condition correctly and could instead report with the logger (most likely `logger.info`)

If we have agreement here on using the logger instead of `raise Exception` . I am happy to work on a PR that we can then review.

**Comment by lukehinds** [comment]
paging @nabilschear and @jetwhiz - let me know your thoughts or context (if I am missing any).

**Comment by nabilschear** [comment]
i think that you've got a good point.  while i love stack traces they can be intimidating

**Comment by nabilschear** [comment]
there's a lot of duplicate log.error and raise Exception pairs that could be deduplicated

**Comment by lukehinds** [comment]
thanks @nabilschear , I will work on this.

**Comment by nabilschear** [comment]
@jetwhiz there's nothing in the webapp that relies upon exceptions right?
