### ISSUE TITLE
Implement CI 

### ISSUE THREAD

**Issue by lukehinds** [keylime/python-keylime#9]
# Description 

Implement automatic build testing / CI 

The idea being that every commit will first undergo a series of automatic unit tests, coding standard checks , security checks etc driven by travis and the result will be posted to the PR review using a github webhook. 

* Create `.travis.yml` file
* Create `requirements.txt` for virtualenv (needed by travis and useful for a pip release and isolated development environments)
* Add build status icons to `README
* Add github webhook to project.`

At a later point add [PEP8](https://www.python.org/dev/peps/pep-0008/) and possibly  [Bandit](https://github.com/PyCQA/bandit) testing, once a bulk of amendments for the above are made.

**Comment by lukehinds** [comment]
Note: this may require a Docker container to run on travis, as there are some unit tests (such as `test_restful.py`) that require a full functional environment that might be hard to achieve in the standard supplied node that travis offers.

**Comment by nabilschear** [comment]
I think we have a docker container built for keylime in our own bamboo build/testing infrastructure.  @jetwhiz can  look into it and figure out if we can just bring that over.

**Comment by lukehinds** [comment]
@nabilschear sounds good, I have one here as well which is builds and runs the unit tests, no strong preference of using mine, I am happy to copy paste anything we need into your Dockerfile.

There work flow would be as follows:

1. Someone makes a PR (preferably from a fork) with a new branch or an `git commit --amend` if its an existing PR.
2. A webhook in travis-ci will invoke a docker build and pull the code from [1] into a Docker volume.
3. The above container will then kick off `run-tests.sh` 
4. The result will be posted to 1.

Over time we can add other checks to the gate (if we want to). [Bandit](https://github.com/PyCQA/bandit) is something that might help us, and I work on the project if we need something extra or fixed.

[You can see an example build here](https://github.com/lukehinds/python-keylime/pull/21) - ignore that its broken at the moment, I just need to fix some PATH stuff which I will do on Monday. 

[Here](https://github.com/lukehinds/python-keylime/blob/master/docker/tests/Dockerfile) is the Dockerfile, key note is that it does not pull or build the python-keylime code, it only preps the environment. We get travis to supply the code, to make sure it has the unmerged pull request code.

**Comment by lukehinds** [comment]
OK, here we go:

https://travis-ci.org/lukehinds/python-keylime-ci-test/builds/476888325?utm_source=github_status&utm_medium=notification

**Comment by jetwhiz** [comment]
This looks great, thanks for all your hard work @lukehinds !  

 

Right now we’re preparing to release Keylime with TPM2 support (hopefully this week), so we should be able to start merging these pull requests in after the new code drop.

**Comment by lukehinds** [comment]
That's fine @jetwhiz , it makes sense to land your code first and then we can remerge these PR's if no conflicts.

**Comment by lukehinds** [comment]
https://github.com/keylime/python-keylime/pull/44

**Comment by lukehinds** [comment]
We can close this now, and future changes can be raised as new issues.
